
resources:
  limits:
    memory: 2G

extraEnvVars:
  DATAJOBS_TELEMETRY_WEBHOOK_ENDPOINT: "https://vcsa.vmware.com/ph-stg/api/hyper/send?_c=taurus.v0&_i=${GIT_USER}"
  LOGGING_LEVEL_COM_VMWARE_TAURUS: DEBUG

vdkOptions: |
  VDK_API_TOKEN_AUTHORIZATION_URL=https://console-stg.cloud.vmware.com/csp/gateway/am/api/auth/api-tokens/authorize
  VDK_CONTROL_SERVICE_REST_API_URL=http://vdk-control-service-svc:8092
  VDK_API_TOKEN=${VDK_API_TOKEN}
  VDK_TRINO_USE_SSL=False
  VDK_TRINO_PORT=1094
  VDK_TRINO_HOST=test-trino-svc

deploymentGitUrl: "github.com/${GIT_USER}/data-jobs.git"
deploymentGitUsername: "${GIT_USER}"
deploymentGitPassword: "${GIT_TOKEN}"
uploadGitReadWriteUsername: "${GIT_USER}"
uploadGitReadWritePassword: "${GIT_TOKEN}"
deploymentDockerRegistryType: generic
deploymentDockerRegistryUsernameReadOnly: "${GIT_USER}"
deploymentDockerRegistryPasswordReadOnly: "${GIT_TOKEN}"
deploymentDockerRegistryUsername: "${GIT_USER}"
deploymentDockerRegistryPassword: "${GIT_TOKEN}"
deploymentDockerRepository: "ghcr.io/${GIT_USER}/data-jobs"
proxyRepositoryURL: "ghcr.io/${GIT_USER}/data-jobs"

security:
  enabled: true
  oauth2:
    jwtJwkSetUri: "https://console-stg.cloud.vmware.com/csp/gateway/am/api/auth/token-public-key?format=jwks"
    jwtIssuerUrl: https://gaz-preview.csp-vidm-prod.com
  authorizationEnabled: true
  authorization:
    webhookUri: https://httpbin.org/post

credentials:
  repository: "EMPTY"

service:
  type: LoadBalancer
