# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0



.build-vdk-sql-extensions:
  variables:
    PLUGIN_NAME: vdk-sql-extensions
  extends: .build-plugin

build-py37-vdk-sql-extensions:
  extends: .build-vdk-sql-extensions
  image: "python:3.7"

build-py311-vdk-sql-extensions:
  extends: .build-vdk-sql-extensions
  image: "python:3.11"

release-vdk-sql-extensions:
  variables:
    PLUGIN_NAME: vdk-sql-extensions
  extends: .release-plugin
