# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

.control_service_retry:
  retry_options:
    max: 1
    when:
      - always

.images:dind:
  image: docker:23.0.1
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:23.0.1-dind

# This grouping listens on changes to all code of control service
# Changes to this group should trigger runs of runs of unit and integration tests.
.control_service_code_changes: &control_service_code_change_locations
  - projects/control-service/cicd/**/*
  - projects/control-service/projects/base/**/*
  - projects/control-service/projects/model/**/*
  - projects/control-service/projects/pipelines_control_service/**/*
  - projects/control-service/projects/settings.gradle
  - projects/control-service/projects/versions-of-external-dependencies.gradle


.control_service_base_build:
  image: docker:23.0.1
  variables:
    _JAVA_OPTIONS: "-Xms2048m -Xmx4096m"
  before_script:
    - apk --no-cache add openjdk17-jdk git zip curl zip py-pip
    - pip install --upgrade pip && pip install awscli

# (there are docker KDC servers that can be used for demo? but it will not work with Impala ?)
# The cockroach storage class is taken from DECC https://devhub.eng.vmware.com/console/resources/namespaces
# Go to the namespace -> StorageClass
.control_service_deploy_testing_data_pipelines:
  stage: pre_release
  image: docker:23.0.1
  script:
    - apk --no-cache add bash openssl curl git gettext zip py-pip
    - pip install --upgrade pip && pip install awscli
    - export FRONTEND_TAG=latest
    - export DESIRED_VERSION=v3.12.0 # helm version
    - curl -LO https://dl.k8s.io/release/v1.27.2/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/bin/kubectl
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - bash -ex ./projects/control-service/cicd/deploy-testing-pipelines-service.sh
  retry: !reference [.control_service_retry, retry_options]

control_service_deploy_testing_data_pipelines:
  extends: .control_service_deploy_testing_data_pipelines
  rules:
    - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
      changes: *control_service_code_change_locations
