# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0



.build-vdk-server:
  variables:
    PLUGIN_NAME: vdk-server
  before_script:
    - apk add --no-cache bash curl python3 py3-pip
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.21.0/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/local/bin/kind
    - kind --version
    - export DESIRED_VERSION=v3.11.3 # helm version 3.11.3
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - helm version
  extends: .build-plugin
  tags:
    - docker

build-py311-vdk-server:
  extends: .build-vdk-server

release-vdk-server:
  variables:
    PLUGIN_NAME: vdk-server
  extends: .release-plugin
